export type QuestionDifficulty = 'easy' | 'medium' | 'hard';
export interface Question { q: string; options: string[]; answer: number; difficulty: QuestionDifficulty }

export const QUESTIONS: Record<string, Question[]> = {
  Quantitative: [
    { q: 'If a train travels 240 km in 4 hours, what is its average speed?', options: ['40 km/h', '60 km/h', '80 km/h', '90 km/h'], answer: 1, difficulty: 'easy' },
    { q: 'What is 15% of 240?', options: ['24', '30', '36', '42'], answer: 2, difficulty: 'easy' },
    { q: 'A product bought for ₹800 is sold at 25% profit. What is the selling price?', options: ['₹900', '₹950', '₹1,000', '₹1,050'], answer: 2, difficulty: 'easy' },
    { q: 'What is the next number: 3, 6, 12, 24, ?', options: ['36', '42', '48', '54'], answer: 2, difficulty: 'easy' },
    { q: 'If x + 7 = 19, what is x?', options: ['10', '11', '12', '13'], answer: 2, difficulty: 'easy' },
    { q: 'A shopkeeper gives 10% discount on an item marked ₹1,500. What is the selling price?', options: ['₹1,350', '₹1,400', '₹1,450', '₹1,490'], answer: 0, difficulty: 'easy' },
    { q: 'The ratio of two numbers is 3:5 and their sum is 64. What is the smaller number?', options: ['18', '21', '24', '27'], answer: 2, difficulty: 'medium' },
    { q: 'A car covers 60 km in 45 minutes. What is its speed in km/h?', options: ['70', '75', '80', '85'], answer: 2, difficulty: 'medium' },
    { q: 'What is 25% of 25% of 160?', options: ['8', '10', '12', '16'], answer: 1, difficulty: 'medium' },
    { q: 'If the simple interest on ₹5,000 for 2 years is ₹500, what is the rate of interest per annum?', options: ['3%', '4%', '5%', '6%'], answer: 2, difficulty: 'medium' },
    { q: 'The average of 5 consecutive even numbers is 16. What is the largest number?', options: ['18', '20', '22', '24'], answer: 1, difficulty: 'medium' },
    { q: 'A man can do a piece of work in 10 days. With his friend, he can do it in 6 days. How many days will the friend alone take?', options: ['12', '15', '18', '20'], answer: 1, difficulty: 'hard' },
    { q: 'What is the compound interest on ₹10,000 at 10% per annum for 2 years?', options: ['₹2,000', '₹2,100', '₹2,200', '₹2,500'], answer: 1, difficulty: 'hard' },
    { q: 'If 3x − 5 = 16, what is x?', options: ['6', '7', '8', '9'], answer: 1, difficulty: 'easy' },
    { q: 'The area of a rectangle is 120 sq cm and its length is 12 cm. What is its perimeter?', options: ['34 cm', '40 cm', '44 cm', '48 cm'], answer: 2, difficulty: 'medium' },
    { q: 'A sum of money doubles in 8 years at simple interest. What is the rate of interest?', options: ['10%', '12.5%', '15%', '20%'], answer: 1, difficulty: 'hard' },
    { q: 'What is the next number: 1, 4, 9, 16, 25, ?', options: ['30', '36', '42', '49'], answer: 1, difficulty: 'easy' },
    { q: 'Two pipes can fill a tank in 10 and 15 minutes respectively. How long will they take together?', options: ['4 min', '5 min', '6 min', '7.5 min'], answer: 2, difficulty: 'hard' },
    { q: 'A box contains 4 red and 6 blue balls. What is the probability of drawing a red ball?', options: ['2/5', '3/5', '1/3', '1/2'], answer: 0, difficulty: 'medium' },
    { q: 'If the cost price of 8 articles equals the selling price of 10, what is the profit/loss percentage?', options: ['20% profit', '20% loss', '25% loss', '25% profit'], answer: 1, difficulty: 'hard' },
    { q: 'What is the value of √(1296) / √(16)?', options: ['7', '8', '9', '10'], answer: 2, difficulty: 'easy' },
  ],
  'Logical Reasoning': [
    { q: 'Which number completes the sequence: 2, 5, 10, 17, 26, ?', options: ['35', '36', '37', '38'], answer: 2, difficulty: 'medium' },
    { q: 'If all roses are flowers and some flowers fade, which is true?', options: ['All roses fade', 'Some roses may fade', 'No roses fade', 'Roses are not flowers'], answer: 1, difficulty: 'medium' },
    { q: 'Find the odd one out.', options: ['Triangle', 'Square', 'Circle', 'Cube'], answer: 3, difficulty: 'easy' },
    { q: 'Book is to Reading as Fork is to:', options: ['Kitchen', 'Eating', 'Cooking', 'Food'], answer: 1, difficulty: 'easy' },
    { q: 'If CAT is coded as DBU, how is DOG coded?', options: ['EPH', 'EPG', 'FPI', 'DPE'], answer: 0, difficulty: 'medium' },
    { q: 'Pointing to a man, a woman said, "His mother is the only daughter of my mother." How is the woman related to the man?', options: ['Mother', 'Sister', 'Aunt', 'Grandmother'], answer: 0, difficulty: 'hard' },
    { q: 'Which number does not belong: 4, 9, 16, 23, 25, 36?', options: ['4', '16', '23', '36'], answer: 2, difficulty: 'medium' },
    { q: 'If FRIEND is coded as GSJFOE, how is CANDLE coded?', options: ['DBOEMF', 'DBOEME', 'DBPFMG', 'DCOEMF'], answer: 0, difficulty: 'hard' },
    { q: 'A clock shows 3:15. What is the angle between the hour and minute hands?', options: ['0°', '7.5°', '15°', '22.5°'], answer: 1, difficulty: 'hard' },
    { q: 'In a row of 30 children, A is 12th from the left. What is A\'s position from the right?', options: ['18th', '19th', '20th', '21st'], answer: 1, difficulty: 'easy' },
    { q: 'Statement: All books are trees. All trees are mountains. Conclusion: All books are mountains. Is the conclusion valid?', options: ['Yes', 'No', 'Cannot be determined', 'Only if trees are tall'], answer: 0, difficulty: 'easy' },
    { q: 'Find the next term: A, C, E, G, ?', options: ['H', 'I', 'J', 'K'], answer: 1, difficulty: 'easy' },
    { q: 'If 5 + 3 = 28, 9 + 1 = 810, then 7 + 2 = ?', options: ['59', '95', '14', '27'], answer: 0, difficulty: 'hard' },
    { q: 'A man walks 3 km north, turns east and walks 4 km. How far is he from the start?', options: ['5 km', '6 km', '7 km', '8 km'], answer: 0, difficulty: 'medium' },
    { q: 'Which word does NOT belong: Apple, Mango, Banana, Carrot, Grapes?', options: ['Apple', 'Mango', 'Carrot', 'Grapes'], answer: 2, difficulty: 'easy' },
    { q: 'If today is Monday, what day will it be 61 days from now?', options: ['Monday', 'Tuesday', 'Wednesday', 'Saturday'], answer: 3, difficulty: 'medium' },
    { q: 'Complete the analogy: Doctor : Hospital :: Teacher : ?', options: ['School', 'Student', 'Class', 'Education'], answer: 0, difficulty: 'easy' },
    { q: 'In a code, if WORK is written as 23-15-18-11, what is REST?', options: ['18-5-19-20', '20-5-19-18', '18-5-20-19', '19-5-18-20'], answer: 0, difficulty: 'medium' },
    { q: 'Which figure continues the series: ○, △, □, ○, △, □, ○, ?, ?', options: ['△, □', '□, ○', '○, △', '△, ○'], answer: 0, difficulty: 'easy' },
    { q: 'A is taller than B, C is shorter than A but taller than D. Who is the shortest?', options: ['A', 'B', 'C', 'D'], answer: 3, difficulty: 'medium' },
    { q: 'If "some pens are pencils" and "all pencils are erasers", which is necessarily true?', options: ['All pens are erasers', 'Some pens are erasers', 'No pens are erasers', 'All erasers are pens'], answer: 1, difficulty: 'medium' },
  ],
  'Verbal Ability': [
    { q: 'Choose the word closest in meaning to "meticulous".', options: ['Careless', 'Thorough', 'Fast', 'Creative'], answer: 1, difficulty: 'easy' },
    { q: 'Choose the correctly spelled word.', options: ['Accomodate', 'Acommodate', 'Accommodate', 'Acomodate'], answer: 2, difficulty: 'easy' },
    { q: 'The manager asked the team to ___ the report.', options: ['revise', 'revise it again', 'revised', 'revising'], answer: 0, difficulty: 'medium' },
    { q: 'Opposite of "scarce" is:', options: ['Rare', 'Limited', 'Abundant', 'Small'], answer: 2, difficulty: 'easy' },
    { q: 'Which sentence is grammatically correct?', options: ['She don\'t like tea.', 'She doesn\'t likes tea.', 'She doesn\'t like tea.', 'She not like tea.'], answer: 2, difficulty: 'medium' },
    { q: 'Choose the synonym of "diligent".', options: ['Lazy', 'Hardworking', 'Careless', 'Slow'], answer: 1, difficulty: 'easy' },
    { q: 'Choose the antonym of "benevolent".', options: ['Kind', 'Generous', 'Malicious', 'Honest'], answer: 2, difficulty: 'medium' },
    { q: 'Fill in the blank: "She has been working here ___ five years."', options: ['since', 'for', 'from', 'at'], answer: 1, difficulty: 'medium' },
    { q: 'Which word means "to make easier or less difficult"?', options: ['Facilitate', 'Complicate', 'Hinder', 'Impede'], answer: 0, difficulty: 'medium' },
    { q: 'Identify the correct sentence.', options: ['He go to school daily.', 'He goes to school daily.', 'He going to school daily.', 'He gone to school daily.'], answer: 1, difficulty: 'easy' },
    { q: 'Choose the correct spelling.', options: ['Neccessary', 'Necessary', 'Neccesary', 'Necesary'], answer: 1, difficulty: 'easy' },
    { q: 'What is the meaning of the idiom "a piece of cake"?', options: ['Very difficult', 'Very easy', 'A dessert', 'A small portion'], answer: 1, difficulty: 'easy' },
    { q: 'Choose the correct article: "I saw ___ honest man."', options: ['a', 'an', 'the', 'no article'], answer: 1, difficulty: 'medium' },
    { q: 'Which is a synonym for "abundant"?', options: ['Plentiful', 'Scarce', 'Empty', 'Minimal'], answer: 0, difficulty: 'easy' },
    { q: 'Rearrange: "always / on time / she / arrives". Which is correct?', options: ['She arrives always on time.', 'Always she arrives on time.', 'She always arrives on time.', 'She on time always arrives.'], answer: 2, difficulty: 'medium' },
    { q: 'Choose the correct form: "Neither of the boys ___ present."', options: ['was', 'were', 'are', 'have'], answer: 0, difficulty: 'hard' },
    { q: 'What is the antonym of "transparent"?', options: ['Clear', 'Opaque', 'Visible', 'Bright'], answer: 1, difficulty: 'medium' },
    { q: 'Fill in the blank: "The committee ___ divided on the issue."', options: ['is', 'are', 'was being', 'be'], answer: 0, difficulty: 'hard' },
    { q: 'Choose the word closest in meaning to "ephemeral".', options: ['Eternal', 'Short-lived', 'Strong', 'Permanent'], answer: 1, difficulty: 'hard' },
    { q: 'Which sentence uses the correct preposition?', options: ['He is good at math.', 'He is good in math.', 'He is good on math.', 'He is good with math.'], answer: 0, difficulty: 'medium' },
    { q: 'Choose the correct passive voice: "She wrote a letter."', options: ['A letter was written by her.', 'A letter is written by her.', 'A letter has been written by her.', 'A letter was being written by her.'], answer: 0, difficulty: 'hard' },
  ],
  'Technical MCQs': [
    { q: 'Which HTTP method is typically used to partially update a resource?', options: ['GET', 'POST', 'PUT', 'PATCH'], answer: 3, difficulty: 'medium' },
    { q: 'What does CSS stand for?', options: ['Computer Style Sheets', 'Cascading Style Sheets', 'Creative Style Syntax', 'Colorful Style Sheets'], answer: 1, difficulty: 'easy' },
    { q: 'Which data structure follows LIFO?', options: ['Queue', 'Array', 'Stack', 'Tree'], answer: 2, difficulty: 'easy' },
    { q: 'What does SQL primarily help you do?', options: ['Style pages', 'Query databases', 'Compile code', 'Design networks'], answer: 1, difficulty: 'easy' },
    { q: 'Which is a JavaScript runtime?', options: ['Node.js', 'Django', 'Laravel', 'Rails'], answer: 0, difficulty: 'easy' },
    { q: 'What is the time complexity of binary search on a sorted array?', options: ['O(n)', 'O(log n)', 'O(n²)', 'O(1)'], answer: 1, difficulty: 'hard' },
    { q: 'Which protocol is used for secure communication on the web?', options: ['HTTP', 'FTP', 'HTTPS', 'SMTP'], answer: 2, difficulty: 'easy' },
    { q: 'What is the default port for HTTP?', options: ['21', '22', '80', '443'], answer: 2, difficulty: 'medium' },
    { q: 'In React, what hook is used for side effects?', options: ['useState', 'useEffect', 'useContext', 'useRef'], answer: 1, difficulty: 'medium' },
    { q: 'Which of these is NOT a JavaScript data type?', options: ['String', 'Boolean', 'Float', 'Number'], answer: 2, difficulty: 'hard' },
    { q: 'What does "git merge" do?', options: ['Combines two branches', 'Deletes a branch', 'Creates a new repo', 'Pushes code'], answer: 0, difficulty: 'easy' },
    { q: 'Which sorting algorithm has the best average time complexity?', options: ['Bubble Sort', 'Selection Sort', 'Quick Sort', 'Insertion Sort'], answer: 2, difficulty: 'hard' },
    { q: 'What is the purpose of Docker?', options: ['Design websites', 'Containerize applications', 'Write tests', 'Manage databases'], answer: 1, difficulty: 'easy' },
    { q: 'Which is NOT a REST API HTTP method?', options: ['GET', 'POST', 'FETCH', 'DELETE'], answer: 2, difficulty: 'medium' },
    { q: 'What does "npm" stand for in the Node ecosystem?', options: ['Node Package Manager', 'New Project Module', 'Network Protocol Module', 'Node Process Manager'], answer: 0, difficulty: 'easy' },
    { q: 'Which CSS property controls spacing inside an element?', options: ['margin', 'padding', 'border', 'spacing'], answer: 1, difficulty: 'easy' },
    { q: 'What is the output of: typeof null in JavaScript?', options: ['"null"', '"undefined"', '"object"', '"number"'], answer: 2, difficulty: 'hard' },
    { q: 'Which database is a NoSQL database?', options: ['PostgreSQL', 'MySQL', 'MongoDB', 'SQLite'], answer: 2, difficulty: 'easy' },
    { q: 'What does the "alt" attribute in an <img> tag provide?', options: ['Image size', 'Alternative text', 'Image source', 'Image title'], answer: 1, difficulty: 'easy' },
    { q: 'Which HTML element is used for the largest heading?', options: ['<h6>', '<head>', '<h1>', '<header>'], answer: 2, difficulty: 'easy' },
    { q: 'What is the Big-O time complexity of accessing an array element by index?', options: ['O(n)', 'O(1)', 'O(log n)', 'O(n²)'], answer: 1, difficulty: 'medium' },
  ],
};

// Role-specific technical banks, grouped into domains so every target role
// (40+ of them) gets genuinely relevant questions without needing one bank
// per exact title. "Technical MCQs" above is the generic fallback used when
// no target role is set or a role can't be mapped to a domain.
export const TECHNICAL_BANKS: Record<string, Question[]> = {
  'Web & Software Development': [
    { q: 'Which of these is a client-side JavaScript UI library?', options: ['Django', 'Laravel', 'React', 'Rails'], answer: 2, difficulty: 'easy' },
    { q: 'What does API stand for?', options: ['Application Programming Interface', 'Applied Program Interface', 'Advanced Programming Interface', 'Application Process Integration'], answer: 0, difficulty: 'easy' },
    { q: 'Which CSS layout module is designed for two-dimensional layouts (rows and columns together)?', options: ['Flexbox', 'Grid', 'Float', 'Table'], answer: 1, difficulty: 'easy' },
    { q: 'Which of these is a version control system?', options: ['Git', 'Docker', 'Jenkins', 'Kubernetes'], answer: 0, difficulty: 'easy' },
    { q: 'In React, which hook lets you memoize the result of an expensive calculation?', options: ['useEffect', 'useMemo', 'useCallback', 'useRef'], answer: 1, difficulty: 'medium' },
    { q: 'What does REST stand for?', options: ['Representational State Transfer', 'Remote State Transfer', 'Representational Server Transfer', 'Relational State Transfer'], answer: 0, difficulty: 'medium' },
    { q: 'Which design pattern restricts a class to a single shared instance?', options: ['Factory', 'Observer', 'Singleton', 'Adapter'], answer: 2, difficulty: 'medium' },
    { q: 'What is the main benefit of adding an index to a database column?', options: ['Reduces storage size', 'Speeds up reads at some cost to writes', 'Removes the need for a primary key', 'Encrypts the column'], answer: 1, difficulty: 'medium' },
    { q: 'What problem does a CDN primarily solve?', options: ['Database scaling', 'Reducing latency by serving content from nearby servers', 'Encrypting passwords', 'Compiling code'], answer: 1, difficulty: 'medium' },
    { q: 'What is the average time complexity of inserting into a hash map?', options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], answer: 0, difficulty: 'hard' },
    { q: 'In a microservices architecture, what does "eventual consistency" mean?', options: ['Data is always instantly consistent', 'Data converges to consistency over time across services', 'Consistency is only checked at startup', 'A single shared database guarantees it'], answer: 1, difficulty: 'hard' },
    { q: 'Which HTTP status code indicates a resource was successfully created?', options: ['200', '201', '204', '301'], answer: 1, difficulty: 'hard' },
  ],
  'Mobile Development': [
    { q: 'Which language is primarily used for native iOS development?', options: ['Kotlin', 'Swift', 'Dart', 'Java'], answer: 1, difficulty: 'easy' },
    { q: 'Which language is primarily used for modern native Android development?', options: ['Kotlin', 'Swift', 'Objective-C', 'Dart'], answer: 0, difficulty: 'easy' },
    { q: 'What does React Native primarily let you build?', options: ['Only Android apps', 'Only iOS apps', 'Cross-platform mobile apps with JavaScript', 'Web apps only'], answer: 2, difficulty: 'easy' },
    { q: 'Which tool is commonly used for automated UI testing of mobile apps?', options: ['Appium', 'Photoshop', 'Docker', 'Figma'], answer: 0, difficulty: 'easy' },
    { q: 'In Flutter, what language is used to write app logic?', options: ['Java', 'Dart', 'Swift', 'Kotlin'], answer: 1, difficulty: 'medium' },
    { q: 'What is the purpose of a mobile app\'s splash screen?', options: ['Show ads', 'Displayed briefly while the app initializes', 'Replace the app icon', 'Handle crashes'], answer: 1, difficulty: 'medium' },
    { q: 'Which storage option best fits small key-value app preferences on mobile?', options: ['A full SQL database', 'AsyncStorage / SharedPreferences', 'An in-memory array only', 'Cloud-only storage'], answer: 1, difficulty: 'medium' },
    { q: 'What does "offline-first" mobile design mean?', options: ['The app only works with internet', 'The app works without connectivity and syncs later', 'The app has no local storage', 'The app skips authentication'], answer: 1, difficulty: 'medium' },
    { q: 'What does app store deployment typically require before release?', options: ['Code signing and store review', 'No configuration at all', 'Only a GitHub push', 'Root access to the device'], answer: 0, difficulty: 'medium' },
    { q: 'Which mobile architecture pattern separates UI, business logic, and observable state?', options: ['MVC', 'MVVM', 'Singleton', 'Monolith'], answer: 1, difficulty: 'hard' },
    { q: 'What is "jank" in mobile UI performance?', options: ['A crash', 'Visible stutter from dropped frames', 'A memory leak', 'A network timeout'], answer: 1, difficulty: 'hard' },
    { q: 'What is a common approach for syncing local mobile data with a server after being offline?', options: ['Silently ignore conflicts', 'Conflict resolution during background sync', 'Delete local data on reconnect', 'Disable the app until online'], answer: 1, difficulty: 'hard' },
  ],
  'Data & AI': [
    { q: 'Which Python library is most associated with dataframes?', options: ['NumPy', 'Pandas', 'Matplotlib', 'Requests'], answer: 1, difficulty: 'easy' },
    { q: 'What does SQL\'s GROUP BY clause do?', options: ['Sorts rows', 'Aggregates rows that share a value', 'Filters out duplicate columns', 'Joins two tables'], answer: 1, difficulty: 'easy' },
    { q: 'Which metric is commonly used to evaluate a classification model?', options: ['RMSE', 'Accuracy', 'R-squared', 'MAE'], answer: 1, difficulty: 'easy' },
    { q: 'Which chart type is best suited for showing a trend over time?', options: ['Pie chart', 'Line chart', 'Scatter plot', 'Heatmap'], answer: 1, difficulty: 'easy' },
    { q: 'What is "overfitting" in machine learning?', options: ['The model performs well on unseen data', 'The model learns noise in training data and performs poorly on new data', 'The model trains too fast', 'The model has too few parameters'], answer: 1, difficulty: 'medium' },
    { q: 'Which technique helps reduce overfitting?', options: ['Adding more layers with no constraints', 'Regularization', 'Removing all training data', 'Increasing the learning rate indefinitely'], answer: 1, difficulty: 'medium' },
    { q: 'In a normalized relational database, what does 3NF primarily eliminate?', options: ['Primary keys', 'Transitive dependencies', 'Indexes', 'Foreign keys'], answer: 1, difficulty: 'medium' },
    { q: 'What does an ETL pipeline stand for?', options: ['Extract, Transform, Load', 'Enter, Track, Log', 'Encode, Transfer, Link', 'Evaluate, Test, Learn'], answer: 0, difficulty: 'medium' },
    { q: 'What does "feature engineering" refer to in ML?', options: ['Writing unit tests', 'Creating or transforming input variables to improve model performance', 'Deploying models to production', 'Designing UI features'], answer: 1, difficulty: 'medium' },
    { q: 'What is the main purpose of a vector database in an ML system?', options: ['Store relational tables', 'Efficient similarity search over embeddings', 'Replace SQL entirely', 'Store raw video only'], answer: 1, difficulty: 'hard' },
    { q: 'Which of these best describes "data leakage" in ML?', options: ['Losing data during transfer', 'Information from outside the training set improperly influencing the model', 'A database backup failure', 'Slow query performance'], answer: 1, difficulty: 'hard' },
    { q: 'In distributed data processing (e.g. Spark), what is a "shuffle"?', options: ['Randomizing row order for display', 'Redistributing data across partitions/nodes for operations like groupBy', 'Encrypting data at rest', 'A UI animation'], answer: 1, difficulty: 'hard' },
  ],
  'Cloud & DevOps': [
    { q: 'What is the primary purpose of Docker?', options: ['Version control', 'Package apps with dependencies into containers', 'Write CSS', 'Manage DNS'], answer: 1, difficulty: 'easy' },
    { q: 'What does CI/CD stand for?', options: ['Continuous Integration / Continuous Delivery', 'Central Index / Central Deploy', 'Code Inspection / Code Deployment', 'Container Init / Container Deploy'], answer: 0, difficulty: 'easy' },
    { q: 'In AWS, what does S3 primarily provide?', options: ['Virtual servers', 'Object storage', 'DNS management only', 'Load balancing only'], answer: 1, difficulty: 'easy' },
    { q: 'Which command-line tool is used to interact with a Kubernetes cluster?', options: ['kubectl', 'docker-compose', 'npm', 'git'], answer: 0, difficulty: 'easy' },
    { q: 'What is the purpose of Kubernetes?', options: ['Write frontend code', 'Orchestrate and scale containerized applications', 'Compile source code', 'Design databases'], answer: 1, difficulty: 'medium' },
    { q: 'What is Infrastructure as Code (IaC)?', options: ['Manually clicking through a cloud console', 'Managing infrastructure through versioned configuration files', 'Writing infra documentation only', 'A monitoring dashboard'], answer: 1, difficulty: 'medium' },
    { q: 'What does a load balancer primarily do?', options: ['Encrypts traffic only', 'Distributes incoming traffic across multiple servers', 'Compiles code', 'Stores logs'], answer: 1, difficulty: 'medium' },
    { q: 'In a blue-green deployment, what is the main benefit?', options: ['Cheaper hosting', 'Near-zero-downtime releases with easy rollback', 'Faster code compilation', 'No need for monitoring'], answer: 1, difficulty: 'medium' },
    { q: 'What is the purpose of a readiness probe / health check in container orchestration?', options: ['Decorative UI', 'Determine if a container instance can safely receive traffic', 'Encrypt secrets', 'Compile images'], answer: 1, difficulty: 'medium' },
    { q: 'What problem does a service mesh (e.g. Istio) primarily address?', options: ['Writing business logic', 'Managing service-to-service traffic, security, and observability', 'Building UI components', 'Compiling containers'], answer: 1, difficulty: 'hard' },
    { q: 'What is the difference between horizontal and vertical scaling?', options: ['They mean the same thing', 'Horizontal adds more machines, vertical adds more resources to one machine', 'Horizontal only applies to databases', 'Vertical scaling is always cheaper'], answer: 1, difficulty: 'hard' },
    { q: 'What does "chaos engineering" aim to do?', options: ['Randomly break production for fun', 'Deliberately inject failures to test system resilience', 'Skip testing entirely', 'Increase deployment frequency without limits'], answer: 1, difficulty: 'hard' },
  ],
  'Cybersecurity': [
    { q: 'What does the OWASP Top 10 primarily list?', options: ['Top programming languages', 'The most critical web application security risks', 'Fastest web frameworks', 'Best UI libraries'], answer: 1, difficulty: 'easy' },
    { q: 'What is the purpose of Nmap?', options: ['Network/port scanning and host discovery', 'Writing exploits automatically', 'Encrypting traffic', 'Editing web pages'], answer: 0, difficulty: 'easy' },
    { q: 'What does SQL injection primarily exploit?', options: ['Weak passwords', 'Unsanitized user input used directly in SQL queries', 'Slow network speed', 'Outdated browsers'], answer: 1, difficulty: 'easy' },
    { q: 'What does the CIA triad in security stand for?', options: ['Confidentiality, Integrity, Availability', 'Central Intelligence Agency', 'Cyber Incident Analysis', 'Control, Integrity, Access'], answer: 0, difficulty: 'easy' },
    { q: 'What is the primary purpose of Burp Suite in web app testing?', options: ['Intercepting and manipulating HTTP traffic', 'Compiling source code', 'Managing DNS records', 'Designing UI mockups'], answer: 0, difficulty: 'medium' },
    { q: 'In penetration testing, what does "reconnaissance" refer to?', options: ['Writing the final report', 'Gathering information about the target before attacking', 'Patching vulnerabilities', 'Cleaning up logs after a test'], answer: 1, difficulty: 'medium' },
    { q: 'What does "privilege escalation" mean in an attack?', options: ['Gaining higher-level access than originally granted', 'Slowing down a network', 'Encrypting a victim\'s files', 'Registering a new domain'], answer: 0, difficulty: 'medium' },
    { q: 'What does CVE stand for in vulnerability management?', options: ['Common Vulnerabilities and Exposures', 'Critical Virus Elimination', 'Certified Vulnerability Engineer', 'Central Vulnerability Encyclopedia'], answer: 0, difficulty: 'medium' },
    { q: 'What does a firewall primarily do?', options: ['Encrypt disk storage', 'Filter network traffic based on rules', 'Compile application code', 'Store user passwords'], answer: 1, difficulty: 'medium' },
    { q: 'What is a key difference between a vulnerability scan and a penetration test?', options: ['They are identical', 'A scan identifies known issues automatically; a pentest actively exploits and validates them', 'A pentest never involves scanning', 'A scan requires exploiting systems'], answer: 1, difficulty: 'hard' },
    { q: 'In Active Directory attacks, what does "Kerberoasting" aim to obtain?', options: ['Encrypted service account password hashes for offline cracking', 'WiFi passwords', 'Physical access badges', 'Email addresses'], answer: 0, difficulty: 'hard' },
    { q: 'What is the purpose of a Metasploit "payload"?', options: ['A documentation template', 'Code executed on a target after successful exploitation', 'A network diagram', 'A firewall rule'], answer: 1, difficulty: 'hard' },
  ],
  'QA & Testing': [
    { q: 'What is the main goal of unit testing?', options: ['Test the whole system end-to-end', 'Verify small, isolated pieces of code work correctly', 'Test UI visual design', 'Test server hardware'], answer: 1, difficulty: 'easy' },
    { q: 'What does "regression testing" verify?', options: ['New features work correctly for the first time', 'Existing functionality still works after changes', 'Only performance under load', 'Only security vulnerabilities'], answer: 1, difficulty: 'easy' },
    { q: 'Which of these is a browser automation testing tool?', options: ['Selenium', 'Photoshop', 'Docker', 'Excel'], answer: 0, difficulty: 'easy' },
    { q: 'What is the purpose of a bug tracking tool like Jira?', options: ['Compile code', 'Log, prioritize, and track defects through resolution', 'Design UI mockups', 'Manage payroll'], answer: 1, difficulty: 'easy' },
    { q: 'What is the difference between black-box and white-box testing?', options: ['Same thing, different names', 'Black-box tests without internal code knowledge; white-box tests with it', 'Black-box only tests UI colors', 'White-box only tests databases'], answer: 1, difficulty: 'medium' },
    { q: 'What is a "test case" primarily composed of?', options: ['Only the expected output', 'Preconditions, steps, and expected results', 'Only the bug ID', 'Server configuration'], answer: 1, difficulty: 'medium' },
    { q: 'What does API testing primarily validate?', options: ['Visual layout', 'Request/response behavior, status codes, and data of an API', 'Font rendering', 'Battery usage'], answer: 1, difficulty: 'medium' },
    { q: 'What is the purpose of a "smoke test"?', options: ['Deep, exhaustive testing of every feature', 'A quick check that critical functionality works before deeper testing', 'Testing only security', 'Load testing at scale'], answer: 1, difficulty: 'medium' },
    { q: 'What does "boundary value analysis" focus on testing?', options: ['Random inputs only', 'Values at the edges of valid input ranges', 'Only invalid inputs', 'UI colors'], answer: 1, difficulty: 'medium' },
    { q: 'What is test-driven development (TDD)?', options: ['Writing tests after all code is complete', 'Writing a failing test before writing the code to pass it', 'Skipping tests to move faster', 'Only testing in production'], answer: 1, difficulty: 'hard' },
    { q: 'What does a "flaky test" mean?', options: ['A test that always fails', 'A test that passes/fails inconsistently without code changes', 'A test with too many assertions', 'A test written in the wrong language'], answer: 1, difficulty: 'hard' },
    { q: 'In performance testing, what does "load testing" specifically measure?', options: ['Code readability', 'System behavior under expected concurrent user load', 'Only single-user response time', 'Database schema design'], answer: 1, difficulty: 'hard' },
  ],
  'Core Engineering': [
    { q: 'What is the SI unit of force?', options: ['Joule', 'Newton', 'Watt', 'Pascal'], answer: 1, difficulty: 'easy' },
    { q: 'In electrical circuits, what does Ohm\'s Law state?', options: ['P = VI', 'V = IR', 'F = ma', 'E = mc²'], answer: 1, difficulty: 'easy' },
    { q: 'In civil engineering, what does a "load-bearing wall" mean?', options: ['A decorative wall only', 'A wall that supports structural weight above it', 'A wall made only of glass', 'A temporary wall'], answer: 1, difficulty: 'easy' },
    { q: 'Which tool is essential for PCB design in embedded systems?', options: ['Photoshop', 'EDA/schematic capture software (e.g. KiCad, Eagle)', 'Excel', 'Word'], answer: 1, difficulty: 'easy' },
    { q: 'What is the primary purpose of a microcontroller in embedded systems?', options: ['Only display graphics', 'Execute control logic and interface with hardware peripherals', 'Store large databases', 'Run a full desktop OS'], answer: 1, difficulty: 'medium' },
    { q: 'In mechanical engineering, what does "fatigue failure" refer to?', options: ['Sudden failure under a single large load', 'Failure from repeated cyclic loading over time', 'Failure due to corrosion only', 'Failure only at high temperature'], answer: 1, difficulty: 'medium' },
    { q: 'What does UART stand for in embedded communication?', options: ['Universal Asynchronous Receiver/Transmitter', 'Unified Analog Radio Transmitter', 'Universal Array Register Type', 'United Access Real-Time'], answer: 0, difficulty: 'medium' },
    { q: 'In structural engineering, what is "reinforced concrete"?', options: ['Concrete mixed with sand only', 'Concrete strengthened internally with steel bars/rebar', 'Concrete without cement', 'Painted concrete'], answer: 1, difficulty: 'medium' },
    { q: 'What is the purpose of a factor of safety in structural design?', options: ['Reduce material cost', 'Account for uncertainties by designing beyond the expected maximum load', 'Speed up construction', 'Reduce weight only'], answer: 1, difficulty: 'medium' },
    { q: 'What is the purpose of a PID controller in embedded/control systems?', options: ['Store data permanently', 'Continuously adjust output to minimize error between setpoint and measured value', 'Compile firmware', 'Manage network traffic'], answer: 1, difficulty: 'hard' },
    { q: 'In electrical engineering, what does "power factor" signify?', options: ['Ratio of real power to apparent power in an AC circuit', 'Total voltage supplied', 'Resistance of a wire', 'Frequency of the signal'], answer: 0, difficulty: 'hard' },
    { q: 'What is the key difference between a real-time OS (RTOS) and a general-purpose OS?', options: ['No difference', 'An RTOS guarantees deterministic response times for critical tasks', 'RTOS always has a graphical interface', 'RTOS cannot run multiple tasks'], answer: 1, difficulty: 'hard' },
  ],
  'Product & Business': [
    { q: 'What does a Product Requirements Document (PRD) primarily define?', options: ['Marketing budget only', 'What is being built, why, and for whom', 'Server architecture', 'Legal contracts'], answer: 1, difficulty: 'easy' },
    { q: 'What is a "sprint" in Agile/Scrum?', options: ['A one-time final release', 'A fixed, short time-boxed period for delivering a work increment', 'A type of bug', 'A yearly planning cycle'], answer: 1, difficulty: 'easy' },
    { q: 'What does MVP stand for in product development?', options: ['Most Valuable Player', 'Minimum Viable Product', 'Major Version Plan', 'Multi-Vendor Platform'], answer: 1, difficulty: 'easy' },
    { q: 'What is the purpose of a Gantt chart?', options: ['Show emotional sentiment', 'Visualize a project schedule and task dependencies over time', 'Track server errors', 'Design a logo'], answer: 1, difficulty: 'easy' },
    { q: 'What is the primary purpose of A/B testing?', options: ['Compare two versions to see which performs better on a metric', 'Test server load only', 'Debug code', 'Design logos'], answer: 0, difficulty: 'medium' },
    { q: 'In project management, what does a "critical path" represent?', options: ['The cheapest task sequence', 'The longest sequence of dependent tasks determining minimum project duration', 'A random task list', 'The last task only'], answer: 1, difficulty: 'medium' },
    { q: 'What is a "stakeholder" in a project?', options: ['Only the CEO', 'Any person or group with interest in or affected by the project\'s outcome', 'Only external customers', 'Only the development team'], answer: 1, difficulty: 'medium' },
    { q: 'What does "churn rate" measure in a business context?', options: ['New customer acquisition speed', 'The percentage of customers who stop using a product over a period', 'Revenue per employee', 'Server uptime'], answer: 1, difficulty: 'medium' },
    { q: 'What is the purpose of a SWOT analysis?', options: ['Financial forecasting only', 'Assessing Strengths, Weaknesses, Opportunities, and Threats', 'Scheduling tasks', 'Writing code specs'], answer: 1, difficulty: 'medium' },
    { q: 'In Scrum, what is the primary role of a Scrum Master?', options: ['Write all the code', 'Facilitate the process and remove impediments for the team', 'Own the product backlog priorities', 'Manage company finances'], answer: 1, difficulty: 'hard' },
    { q: 'What does "runway" mean for a startup?', options: ['Distance to the office', 'How long the company can operate before running out of cash', 'Marketing reach', 'Product release date'], answer: 1, difficulty: 'hard' },
    { q: 'In business analysis, what is the purpose of a "user story"?', options: ['Legal documentation', 'A short, plain-language description of a feature from an end-user\'s perspective', 'Server configuration', 'A financial report'], answer: 1, difficulty: 'hard' },
  ],
  'Design & Marketing': [
    { q: 'What does UX stand for?', options: ['User Experience', 'User Extension', 'Unified Xperience', 'User Exchange'], answer: 0, difficulty: 'easy' },
    { q: 'What is the primary purpose of wireframing?', options: ['Final polished visuals', 'A low-fidelity structural layout to plan content and flow', 'Writing backend code', 'SEO optimization'], answer: 1, difficulty: 'easy' },
    { q: 'What does SEO stand for?', options: ['Search Engine Optimization', 'Social Engagement Outreach', 'Site Efficiency Operations', 'Server Endpoint Optimization'], answer: 0, difficulty: 'easy' },
    { q: 'In content writing, what does "tone of voice" refer to?', options: ['Font size', 'The distinct personality and style used in written communication', 'Page load speed', 'Image resolution'], answer: 1, difficulty: 'easy' },
    { q: 'What is the purpose of a design system?', options: ['A single one-off mockup', 'A reusable set of components and guidelines for consistent design', 'A marketing calendar', 'A database schema'], answer: 1, difficulty: 'medium' },
    { q: 'What does accessibility (a11y) in design primarily address?', options: ['Making designs colorful', 'Making products usable by people with disabilities', 'Reducing file size', 'Faster page load only'], answer: 1, difficulty: 'medium' },
    { q: 'What is A/B testing commonly used for in marketing?', options: ['Comparing two ad/page versions to see which converts better', 'Fixing bugs', 'Compiling code', 'Managing servers'], answer: 0, difficulty: 'medium' },
    { q: 'What is the purpose of a call-to-action (CTA) in marketing content?', options: ['A legal disclaimer', 'Prompt the user to take a specific next action', 'Decorative text only', 'SEO keyword stuffing'], answer: 1, difficulty: 'medium' },
    { q: 'What does "usability testing" primarily evaluate?', options: ['Server response time', 'Whether real users can complete tasks effectively with a design', 'Code quality', 'Ad spend efficiency'], answer: 1, difficulty: 'medium' },
    { q: 'What is the purpose of user personas in product design?', options: ['Legal user agreements', 'Represent archetypes of real user groups to guide design decisions', 'Track server logs', 'Manage billing'], answer: 1, difficulty: 'hard' },
    { q: 'What is the primary goal of conversion rate optimization (CRO)?', options: ['Increase the percentage of visitors who complete a desired action', 'Increase server uptime', 'Reduce code complexity', 'Improve font rendering'], answer: 0, difficulty: 'hard' },
    { q: 'What does "design thinking" primarily emphasize?', options: ['Skipping user research', 'A human-centered, iterative process: empathize, define, ideate, prototype, test', 'Writing code first', 'Only visual aesthetics'], answer: 1, difficulty: 'hard' },
  ],
};

const ROLE_TECHNICAL_DOMAIN: Record<string, string> = {
  'full stack developer': 'Web & Software Development',
  'frontend developer': 'Web & Software Development',
  'backend developer': 'Web & Software Development',
  'software architect': 'Web & Software Development',
  'web developer': 'Web & Software Development',
  'game developer': 'Web & Software Development',
  'blockchain developer': 'Web & Software Development',
  'mobile app developer': 'Mobile Development',
  'data analyst': 'Data & AI',
  'data scientist': 'Data & AI',
  'machine learning engineer': 'Data & AI',
  'ai engineer': 'Data & AI',
  'data engineer': 'Data & AI',
  'business intelligence analyst': 'Data & AI',
  'statistician': 'Data & AI',
  'devops engineer': 'Cloud & DevOps',
  'cloud engineer': 'Cloud & DevOps',
  'database administrator': 'Cloud & DevOps',
  'vapt analyst / penetration tester': 'Cybersecurity',
  'penetration tester': 'Cybersecurity',
  'cybersecurity analyst': 'Cybersecurity',
  'soc analyst': 'Cybersecurity',
  'web app security engineer': 'Cybersecurity',
  'qa / test engineer': 'QA & Testing',
  'civil engineer': 'Core Engineering',
  'mechanical engineer': 'Core Engineering',
  'electrical engineer': 'Core Engineering',
  'embedded systems engineer': 'Core Engineering',
  'product manager': 'Product & Business',
  'project manager': 'Product & Business',
  'scrum master': 'Product & Business',
  'business analyst': 'Product & Business',
  'financial analyst': 'Product & Business',
  'hr specialist': 'Product & Business',
  'operations analyst': 'Product & Business',
  'operations coordinator': 'Product & Business',
  'executive assistant': 'Product & Business',
  'ui/ux designer': 'Design & Marketing',
  'product designer': 'Design & Marketing',
  'graphic designer': 'Design & Marketing',
  'digital marketer': 'Design & Marketing',
  'content writer': 'Design & Marketing',
};

// Keyword fallback for a target role picked via free-text "Other" that
// doesn't exactly match the lookup above — mirrors the category-inference
// approach already used for company matching on the server.
function inferTechnicalDomain(lowerRole: string): string | undefined {
  const has = (...words: string[]) => words.some((w) => lowerRole.includes(w));
  if (has('security', 'vapt', 'penetration', 'soc', 'cyber', 'threat')) return 'Cybersecurity';
  if (has('data', 'machine learning', 'ml ', 'ai ', 'analytics', 'statistic')) return 'Data & AI';
  if (has('devops', 'cloud', 'infra', 'database administrator', 'site reliability')) return 'Cloud & DevOps';
  if (has('qa', 'test engineer', 'quality')) return 'QA & Testing';
  if (has('mobile', 'android', 'ios', 'flutter')) return 'Mobile Development';
  if (has('civil', 'mechanical', 'electrical', 'embedded', 'hardware', 'vlsi')) return 'Core Engineering';
  if (has('product manager', 'project manager', 'scrum', 'business analyst', 'financial', 'hr ', 'operations', 'assistant')) return 'Product & Business';
  if (has('design', 'ux', 'ui', 'marketing', 'content writer', 'graphic')) return 'Design & Marketing';
  if (has('developer', 'engineer', 'architect')) return 'Web & Software Development';
  return undefined;
}

export function getTechnicalDomain(targetRole?: string): string | undefined {
  if (!targetRole) return undefined;
  const key = targetRole.trim().toLowerCase();
  return ROLE_TECHNICAL_DOMAIN[key] || inferTechnicalDomain(key);
}

// Falls back to the generic "Technical MCQs" bank when no target role is set
// or it can't be mapped to a domain (e.g. Entry-Level / Trainee Associate).
export function getTechnicalBank(targetRole?: string): Question[] {
  const domain = getTechnicalDomain(targetRole);
  return (domain && TECHNICAL_BANKS[domain]) || QUESTIONS['Technical MCQs'];
}
